### PR TITLE
Merging AIDA and VMAP into LORELEI (Feb 2019)

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
Kevin or Rachel, can you please do a thorough test and verify that this code works with the LORELEI dashboards / datasets ?

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
Also, so we don't screw up this week's demos, I won't merge this until AFTER the 20th.

**Review by rartiss55 — APPROVED** [review]
Checked against Transition Partner and Humanity Roads config files. I didn't notice any issues with the merge specifically, but:
- I previously logged a bug with the database/table not updating properly in the filters panel when switching between dashboards. Looks like the filters previously selected don't update properly either in this case, and I made a note in the original ticket here: https://nextcentury.atlassian.net/browse/THOR-1039
- Noticed an issue with the timeline component in dual view for the Humanity Roads config, and logged a ticket for that as well: https://nextcentury.atlassian.net/browse/THOR-1055

**Review by rartiss55 — DISMISSED** [review]

**Review by rartiss55 — CHANGES_REQUESTED** [review]
Looks like a couple media viewer tests are failing -- probably due to that recent change that removed video elements.

**Comment by ThomasSchellenbergNextCentury** [comment]
@rartiss55  Doh!  Silly me.  I broke my own rules!  Thanks for finding that.  It should be fixed now.

I was, uhh, testing you... And you passed.  Good job!

**Review by rartiss55 — APPROVED** [review]

**Pull request merged**
