### PR TITLE
Lorelei merge angular7

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
@Konnoke can you please make sure that the Angular 7 update works with LORELEI's datasets and dashboards?  No rush.  Thanks!

PS:  If your widgets are not in the correct order within the grid layout, your config file is likely the issue.  For example, I noticed that the LORELEI July 2018 Demo config has miscalculated rows/columns.  The new version of angular2-grid seems to work a bit differently if you have miscalculations in your config.

### CODE REVIEW

**Comment by Konnoke** [comment]
I get this from terminal: 
`WARNING in ./node_modules/neon-framework/node_modules/node-uuid/uuid.js
Module not found: Error: Can't resolve 'crypto' in '/home/HQ/kbaik/git/neon-dash-internal/node_modules/neon-framework/node_modules/node-uuid'
ℹ ｢wdm｣: Compiled with warnings.
`

and this error from the Network graph 

`NetworkGraphComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property 'type' of undefined
    at NetworkGraphComponent.push../src/app/components/base-neon-component/base-neon.component.ts.BaseNeonComponent.datifyWherePredicates (base-neon.component.ts:1207)
    at NetworkGraphComponent.push../src/app/components/base-neon-component/base-neon.component.ts.BaseNeonComponent.executeQuery (base-neon.component.ts:767)
    at NetworkGraphComponent.push../src/app/components/base-neon-component/base-neon.component.ts.BaseNeonComponent.executeQueryChain (base-neon.component.ts:519)
    at NetworkGraphComponent.push../src/app/components/base-neon-component/base-neon.component.ts.BaseNeonComponent.ngAfterViewInit (base-neon.component.ts:137)
    at callProviderLifecycles (core.js:20961)
    at callElementProvidersLifecycles (core.js:20935)
    at callLifecycleHooksChildrenFirst (core.js:20925)
    at checkAndUpdateView (core.js:21861)
    at callViewAction (core.js:22093)
    at execEmbeddedViewsAction (core.js:22056)`

Besides that everything else seems to works with LORELEI's datasets and dashboards

**Comment by ThomasSchellenbergNextCentury** [comment]
@Konnoke Concerning the Network Graph bug:  Bao found the same issue and I just fixed it and merged it into this branch.  Concerning the Warning:  I think that's something we'll have to live with for the moment.

**Review by Konnoke — APPROVED** [review]
There's another error from the network graph where it doesn't show any visual but it shows the correct count.

image

`ERROR RangeError: Maximum call stack size exceeded
    at ForceAtlas2BasedRepulsionSolver._insertRegion (vis.js:28115)
    at ForceAtlas2BasedRepulsionSolver._splitBranch (vis.js:28093)
    at ForceAtlas2BasedRepulsionSolver._placeInRegion (vis.js:28061)
    at ForceAtlas2BasedRepulsionSolver._placeInTree`

**Comment by ThomasSchellenbergNextCentury** [comment]
@Konnoke I'm seeing the same behavior in the Angular 5 version, so, while we should investigate this bug, I don't think it's related to the Angular 7 upgrade.

**Pull request merged**
