### PR TITLE
Lorelei merge 122018

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
@rartiss55 Here is the merge from AIDA.  Could you please ensure that it works with the LORELEI dashboards and datasets?  Thanks.

### CODE REVIEW

**Comment by rartiss55** [comment]
@ThomasSchellenbergNextCentury I noticed a missing image link in the visualizations for a taxonomy viewer.

**Comment by rartiss55** [comment]
@ThomasSchellenbergNextCentury Checked against the following LORELEI config files/related datasets:
- config.TransitionPartner.json
- config.darpa-July2018.json

And looks like things are working fine. @wagnerwj are there any other config files/datasets I should check?

**Comment by wagnerwj** [comment]
Those will do. Any other changes I'll make

**Comment by ThomasSchellenbergNextCentury** [comment]
While not ideal, let's handle the taxonomy viewer icon as a separate task.

**Pull request merged**
