### PR TITLE
THOR-1236 Filter Labels

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
Goals:  Unify the code that generates the filter labels.

Accomplishments:
- Removed the code to generate filter labels from the Current Filters Component.
- Updated the code to generate filter labels in the Abstract Filter classes.  Compound Filters now generate specific labels if they correspond to specific designs like bounds, domain, or list.

### CODE REVIEW

**Comment by arciisine** [comment]
The geo field name needs to be shortened, currently it shows as `(geoLocation.lat and geoLocation.lon)`, and should show as `geoLocation`.

**Comment by ThomasSchellenbergNextCentury** [comment]
> The geo field name needs to be shortened, currently it shows as `(geoLocation.lat and geoLocation.lon)`, and should show as `geoLocation`.

@arciisine Respectfully disagree.
1. That won't work if the latitude and longitude fields aren't in the same parent object.
2. That's a bit misleading since the "geoLocation" object contains other properties.  We're not filtering on geoLocation.hash.

**Comment by arciisine** [comment]
Also would recommend dropping the `=` from the label, as that should be indicated purely by it's presence.

**Comment by arciisine** [comment]
Complex filters need to be truncated, `(entities.name and entities.translation and entities.translation)
(contains a and contains b and contains e)` is not clear and it takes up a lot of space.

**Comment by arciisine** [comment]
> > The geo field name needs to be shortened, currently it shows as `(geoLocation.lat and geoLocation.lon)`, and should show as `geoLocation`.
> 
> @arciisine Respectfully disagree.
> 
> 1. That won't work if the latitude and longitude fields aren't in the same parent object.
> 2. That's a bit misleading since the "geoLocation" object contains other properties.  We're not filtering on geoLocation.hash.

I think it would be clear enough when looking at coordinate pairs.  Going for the 99% use case here, the extra space used in the filter bar is less than ideal.  If you are mixing/matching different fields for lat/lon then I would totally agree on showing both fields.

**Comment by ThomasSchellenbergNextCentury** [comment]
@arciisine Thank you for the good suggestions.  I've:

1. Hidden the `=` operator.
2. Combined multiple filter fields that belong to common parent objects (like geoLocation).
3. Shortened labels of custom compound filters (though I'm sure we'll want to continue thinking about better ways to show them, as represented by ticket THOR-1333).

Please let me know if you have any more thoughts.

**Comment by arciisine** [comment]
The custom filters still do not show the appropriate structure. `entities.end_char and entities.name
[ contains (a, ) and b ]` still looks confusing and wrong.

**Comment by ThomasSchellenbergNextCentury** [comment]
@arciisine I've added a placeholder for empty string values.  For custom compound filters, I've moved the fields into the chip in order to make it look better.  Please let me know if you like it.

**Pull request merged**
