### PR TITLE
THOR-847 THOR-854 ColorSchemeService color list simplification

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
First in a series of changes to the ColorSchemeService.

In this change, I've removed the overly complicated behavior of managing multiple color lists.  I've updated the single color list to use the new color theme designed by UX.  Right now we're just using the Teal theme colors but eventually the colors will change based on the selected theme.

Stacey, I've also removed the custom color behavior in the Network Graph.  Please make sure that this change still works with the AIDA data or if we need to add new custom behavior.  I think eventually we should allow you to set custom node colors using the config file but that can be a future task.

Please let me know if you have any questions.  Thanks!

### CODE REVIEW

**Review by gitnordt — CHANGES_REQUESTED** [review]
AIDA will still need a way to apply custom colors to the network graph. The colors listed in the ColorSet are unappealing and make it difficult to read the node text. 

unappealingcolors

Do we need to modify the config file and network graph to include access to these colors?
        [   //3 colors - defined palette	
            new Color(173, 216, 230),	
            new Color(223, 159, 159),	
            new Color(255, 218, 153)	
        ]

**Comment by ThomasSchellenbergNextCentury** [comment]
@snorpet I think the ideal solution would be to use the config file to set custom color lists that the network graph (or other specific widgets) would use instead of the default theme-based colors.

Would you like that implemented before we merge-in this change?  (It may not be too hard -- I can take a look tomorrow.)

**Comment by gitnordt** [comment]
@thomasSchellenbergNextCentury I believe I had the colors set in the config before I realized we were using a color service. I might be able to find the code fairly easily.

**Comment by ThomasSchellenbergNextCentury** [comment]
@snorpet I think there's a colorMaps option in the config but I don't think anything in the code is actually using it right now...

**Comment by gitnordt** [comment]
> @ThomasSchellenbergNextCentury I believe I had the colors set in the config before I realized we were using a color service. I might be able to find the code fairly easily.



> @snorpet I think there's a colorMaps option in the config but I don't think anything in the code is actually using it right now...

@ThomasSchellenbergNextCentury  I will put in a separate ticket for this one and make the changes.

**Review by gitnordt — APPROVED** [review]

**Pull request merged**
