### PR TITLE
THOR-1103 Map Bounds Redraw

### PR DESCRIPTION
**Pull request by arciisine**
Redraw map bounds when filter set programmatically

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
@arciisine I don't think you'll be able to properly resolve this issue until THOR-1166-Dark-Theme is merged into lorelei-master since that affects how both the theme-change and the dashboard-refresh behavior is handled.

**Comment by arciisine** [comment]
I don't think this relies on any of those changes, it only added on to an existing method to draw the boundary if the geo bounds are provided.  If that logic has changed, then I would concur this should be affected.

**Comment by Konnoke** [comment]
I merged the Dark theme branch in order to test it out and it works!


ezgif com-video-to-gif

**Review by Konnoke — APPROVED** [review]

**Comment by ThomasSchellenbergNextCentury** [comment]
So, I totally confused this task with THOR-1277 (the map zoom refresh bug), and thus my earlier comment.  Sorry about that.

Thanks to Kevin for the video!  Looks like everything is working properly.

**Pull request merged**
