### PR TITLE
Aida 568

### PR DESCRIPTION
**Pull request by gitnordt**

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
@snorpet The Thumbnail Grid unit tests were stalling.  I fixed them so they don't stall, but other Thumbnail Grid tests are now failing.  Could you please take a look?

Also, could you please add a few tests for manageFieldFilters?

**Comment by gitnordt** [comment]
> @snorpet The Thumbnail Grid unit tests were stalling. I fixed them so they don't stall, but other Thumbnail Grid tests are now failing. Could you please take a look?
> 
> Also, could you please add a few tests for manageFieldFilters?

Sorry about that. Thank you for the feedback, I will take a look.

**Comment by gitnordt** [comment]
@ThomasSchellenbergNextCentury  I went down a bit of a rabbit hole with these tests. It seemed like for every one that I fixed, two more broke. I believe I finally have them all working again and have added a few new tests for the manageFieldFilters function I added. Let me know how it goes. Thanks!

**Comment by ThomasSchellenbergNextCentury** [comment]
@snorpet I don't think I see an actual example of `filterFields` being used by a `thumbnailGrid` in your config file, but I trust that you know what you're doing!  :)

**Review by ThomasSchellenbergNextCentury — DISMISSED** [review]

**Comment by gitnordt** [comment]
> @snorpet I don't think I see an actual example of `filterFields` being used by a `thumbnailGrid` in your config file, but I trust that you know what you're doing! :)

@ThomasSchellenbergNextCentury Good good...pushed updated config.If you don't mind, can you approve this one more time?

**Comment by ThomasSchellenbergNextCentury** [comment]
Absolutely!  Seems to be working on my computer too.  Thanks!

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]

**Pull request merged**
